# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='tot',
            field=models.IntegerField(default=0),
        ),
    ]
