# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_tot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='tot',
        ),
    ]
